[package]
name = "shared_between_host_and_guest"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
alloy-sol-types = { version = "0.4.2" }
anyhow = "1.0"

[lib]
path = "src/lib.rs"