name: main

on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUST_BACKTRACE: "1"
  RISC0_MONOREPO_REF: "release-1.1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - name: checkout dummy commit (submodule bug workaround)
        run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust
        uses: risc0/risc0/.github/actions/rustup@main

      - name: Install Foundry
        uses: risc0/foundry-toolchain@2fe7e70b520f62368a0e3c464f997df07ede420f

      - name: risczero toolchain install
        uses: risc0/risc0-ethereum/.github/actions/cargo-risczero-install@release-1.1
        with:
          ref: ${{ env.RISC0_MONOREPO_REF }}

      - name: build rust guest
        run: cargo build

      - name: build solidity contracts
        run: forge build

      - name: run tests
        run: cargo test

      - name: run foundry tests in dev mode
        env:
            RISC0_DEV_MODE: true
        run: forge test -vvv

  integration-test:
    name: integration test
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - name: checkout dummy commit (submodule bug workaround)
        run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust
        uses: risc0/risc0/.github/actions/rustup@main

      - name: Install Foundry
        uses: risc0/foundry-toolchain@2fe7e70b520f62368a0e3c464f997df07ede420f

      - name: risczero toolchain install
        uses: risc0/risc0-ethereum/.github/actions/cargo-risczero-install@release-1.1
        with:
          ref: ${{ env.RISC0_MONOREPO_REF }}

      - name: build rust guest
        run: cargo build

      - name: build solidity contracts
        run: forge build

      - name: run foundry tests with local prover
        env:
          RISC0_DEV_MODE: false
        run: forge test -vvv

      - name: Launch anvil
        run: nohup anvil > anvil.log 2>&1 &

      - name: Make sure anvil is running
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8545/health; then
              echo "Anvil is running!"
              exit 0
            fi
            echo "Waiting for Anvil to start..."
            sleep 5
          done
          echo "Anvil did not start in time!" && exit 1

      - name: run CLI test
        run: python3 cli/test.py
